const fs = require('fs');
const path = require('path');

// 300個のユニークなホテル英語フレーズを直接定義
const cleanPhrases = [
  // Check-in (30 phrases)
  { english: 'Welcome to our hotel. Do you have a reservation?', japanese: 'ようこそ。当ホテルのご予約はございますか？', category: 'Check-in' },
  { english: 'May I have your passport, please?', japanese: 'パスポートを拝見できますか？', category: 'Check-in' },
  { english: 'Please fill out this registration form.', japanese: 'こちらの宿泊カードにご記入をお願いします。', category: 'Check-in' },
  { english: 'Check-in time is from 3 PM.', japanese: 'チェックインは午後3時からです。', category: 'Check-in' },
  { english: 'How many nights will you be staying?', japanese: '何泊のご予定ですか？', category: 'Check-in' },
  { english: 'Do you have any special requests?', japanese: '何かご要望はございますか？', category: 'Check-in' },
  { english: 'Your room number is 1205.', japanese: 'お部屋番号は1205号室です。', category: 'Check-in' },
  { english: 'Here is your room key.', japanese: 'こちらがお部屋のキーです。', category: 'Check-in' },
  { english: 'Breakfast is included in your stay.', japanese: '朝食はご宿泊料金に含まれております。', category: 'Check-in' },
  { english: 'The bellboy will help you with your luggage.', japanese: 'ベルボーイがお荷物のお手伝いをいたします。', category: 'Check-in' },
  { english: 'Your room is ready now.', japanese: 'お部屋のご用意ができました。', category: 'Check-in' },
  { english: 'Please sign here.', japanese: 'こちらにサインをお願いします。', category: 'Check-in' },
  { english: 'Do you need a wake-up call?', japanese: 'モーニングコールは必要ですか？', category: 'Check-in' },
  { english: 'The elevator is over there.', japanese: 'エレベーターはあちらです。', category: 'Check-in' },
  { english: 'Your room is on the 5th floor.', japanese: 'お部屋は5階にございます。', category: 'Check-in' },
  { english: 'Is this your first time staying with us?', japanese: '当ホテルへのご宿泊は初めてですか？', category: 'Check-in' },
  { english: 'Do you have any dietary restrictions?', japanese: '食事制限はございますか？', category: 'Check-in' },
  { english: 'We have a special package for you.', japanese: '特別なパッケージをご用意しております。', category: 'Check-in' },
  { english: 'Please keep your room key with you.', japanese: 'お部屋のキーはお持ちください。', category: 'Check-in' },
  { english: 'The hotel has 24-hour room service.', japanese: '24時間ルームサービスがございます。', category: 'Check-in' },
  { english: 'Would you like a city map?', japanese: '市街地図はいかがですか？', category: 'Check-in' },
  { english: 'The concierge can help with reservations.', japanese: 'コンシェルジュが予約のお手伝いをいたします。', category: 'Check-in' },
  { english: 'Your luggage will be delivered to your room.', japanese: 'お荷物はお部屋までお届けいたします。', category: 'Check-in' },
  { english: 'Please don\'t hesitate to ask if you need anything.', japanese: '何かご不明な点がございましたら、お気軽にお声かけください。', category: 'Check-in' },
  { english: 'The hotel provides free shuttle service.', japanese: '無料シャトルサービスがございます。', category: 'Check-in' },
  { english: 'Your room has a beautiful ocean view.', japanese: 'お部屋から美しい海の景色がご覧いただけます。', category: 'Check-in' },
  { english: 'We have complimentary coffee in the lobby.', japanese: 'ロビーで無料のコーヒーをご提供しております。', category: 'Check-in' },
  { english: 'The hotel offers free parking.', japanese: '無料駐車場がございます。', category: 'Check-in' },
  { english: 'Please take the elevator to your floor.', japanese: 'エレベーターでお部屋の階までお上がりください。', category: 'Check-in' },
  { english: 'We hope you enjoy your stay with us.', japanese: '快適なご滞在をお過ごしください。', category: 'Check-in' },

  // Check-out (30 phrases)
  { english: 'Check-out is until 11 AM.', japanese: 'チェックアウトは午前11時までです。', category: 'Check-out' },
  { english: 'Did you enjoy your stay?', japanese: 'ご滞在はいかがでしたか？', category: 'Check-out' },
  { english: 'May I have your room key, please?', japanese: 'お部屋の鍵をお預かりできますか？', category: 'Check-out' },
  { english: 'Would you like to pay by cash or credit card?', japanese: 'お支払いは現金ですか、カードですか？', category: 'Check-out' },
  { english: 'Here is your receipt.', japanese: 'こちらが領収書です。', category: 'Check-out' },
  { english: 'Would you like to settle your bill?', japanese: 'お会計はいかがいたしましょうか？', category: 'Check-out' },
  { english: 'How would you like to pay?', japanese: 'お支払い方法はいかがいたしますか？', category: 'Check-out' },
  { english: 'We accept credit cards and cash.', japanese: 'クレジットカードと現金でお支払いいただけます。', category: 'Check-out' },
  { english: 'Thank you for staying with us.', japanese: 'ご利用いただき、ありがとうございました。', category: 'Check-out' },
  { english: 'We hope you enjoyed your stay.', japanese: 'ご滞在はいかがでしたでしょうか。', category: 'Check-out' },
  { english: 'Is there anything else I can help you with?', japanese: '他にご不明な点はございますか？', category: 'Check-out' },
  { english: 'Please don\'t forget your belongings.', japanese: 'お忘れ物のないようお気をつけください。', category: 'Check-out' },
  { english: 'Would you like us to store your luggage?', japanese: 'お荷物をお預かりしましょうか？', category: 'Check-out' },
  { english: 'The taxi will be here in 5 minutes.', japanese: 'タクシーは5分後に参ります。', category: 'Check-out' },
  { english: 'Please rate your stay on our website.', japanese: '当ホテルのウェブサイトで評価をお願いいたします。', category: 'Check-out' },
  { english: 'We look forward to seeing you again.', japanese: 'またのご利用をお待ちしております。', category: 'Check-out' },
  { english: 'Have a safe trip home.', japanese: 'お気をつけてお帰りください。', category: 'Check-out' },
  { english: 'Your bill has been settled.', japanese: 'お会計は完了いたしました。', category: 'Check-out' },
  { english: 'Please sign the receipt.', japanese: '領収書にサインをお願いします。', category: 'Check-out' },
  { english: 'The hotel shuttle will take you to the airport.', japanese: 'ホテルシャトルで空港までお送りいたします。', category: 'Check-out' },
  { english: 'Would you like a copy of your bill?', japanese: '請求書のコピーはいかがですか？', category: 'Check-out' },
  { english: 'Please return your room key.', japanese: 'お部屋のキーをお返しください。', category: 'Check-out' },
  { english: 'The hotel offers express check-out service.', japanese: 'エクスプレスチェックアウトサービスがございます。', category: 'Check-out' },
  { english: 'Your account has been charged to your credit card.', japanese: 'お客様のクレジットカードに請求いたしました。', category: 'Check-out' },
  { english: 'Please check your room before leaving.', japanese: 'お部屋を出る前にご確認ください。', category: 'Check-out' },
  { english: 'The hotel provides free airport transfer.', japanese: '無料空港送迎サービスがございます。', category: 'Check-out' },
  { english: 'Would you like to join our loyalty program?', japanese: 'ロイヤリティプログラムにご参加いかがですか？', category: 'Check-out' },
  { english: 'Please take our business card.', japanese: '当ホテルの名刺をお持ちください。', category: 'Check-out' },
  { english: 'The hotel has a late check-out option.', japanese: 'レイトチェックアウトオプションがございます。', category: 'Check-out' },
  { english: 'Thank you for choosing our hotel.', japanese: '当ホテルをお選びいただき、ありがとうございました。', category: 'Check-out' },

  // Facilities (30 phrases)
  { english: 'Breakfast is served from 7 AM to 10 AM.', japanese: '朝食は午前7時から10時までです。', category: 'Facilities' },
  { english: 'The elevator is over there.', japanese: 'エレベーターはあちらです。', category: 'Facilities' },
  { english: 'Free Wi-Fi is available in all rooms.', japanese: '全客室で無料Wi-Fiをご利用いただけます。', category: 'Facilities' },
  { english: 'The gym is on the second floor.', japanese: 'ジムは2階にございます。', category: 'Facilities' },
  { english: 'The swimming pool is open until 9 PM.', japanese: 'プールは午後9時まで営業しています。', category: 'Facilities' },
  { english: 'The spa is open 24 hours.', japanese: 'スパは24時間営業しております。', category: 'Facilities' },
  { english: 'The business center is on the mezzanine floor.', japanese: 'ビジネスセンターは中2階にございます。', category: 'Facilities' },
  { english: 'We have free Wi-Fi throughout the hotel.', japanese: 'ホテル内全域で無料Wi-Fiをご利用いただけます。', category: 'Facilities' },
  { english: 'The laundry service is available 24 hours.', japanese: 'ランドリーサービスは24時間ご利用いただけます。', category: 'Facilities' },
  { english: 'The conference room can accommodate 50 people.', japanese: '会議室は50名までご利用いただけます。', category: 'Facilities' },
  { english: 'The restaurant is on the ground floor.', japanese: 'レストランは1階にございます。', category: 'Facilities' },
  { english: 'We have a swimming pool and gym.', japanese: 'プールとジムがございます。', category: 'Facilities' },
  { english: 'The bar is open until midnight.', japanese: 'バーは深夜12時まで営業しています。', category: 'Facilities' },
  { english: 'The hotel has a rooftop terrace.', japanese: '屋上テラスがございます。', category: 'Facilities' },
  { english: 'Room service is available 24 hours.', japanese: '24時間ルームサービスがございます。', category: 'Facilities' },
  { english: 'The hotel offers free parking.', japanese: '無料駐車場がございます。', category: 'Facilities' },
  { english: 'The hotel has a gift shop.', japanese: 'ギフトショップがございます。', category: 'Facilities' },
  { english: 'The hotel provides free shuttle service.', japanese: '無料シャトルサービスがございます。', category: 'Facilities' },
  { english: 'The hotel has a beauty salon.', japanese: '美容室がございます。', category: 'Facilities' },
  { english: 'The hotel offers currency exchange.', japanese: '両替サービスがございます。', category: 'Facilities' },
  { english: 'The hotel has a tour desk.', japanese: 'ツアーデスクがございます。', category: 'Facilities' },
  { english: 'The hotel provides free newspapers.', japanese: '無料新聞をご提供しております。', category: 'Facilities' },
  { english: 'The hotel has a library.', japanese: '図書室がございます。', category: 'Facilities' },
  { english: 'The hotel offers babysitting services.', japanese: 'ベビーシッターサービスがございます。', category: 'Facilities' },
  { english: 'The hotel has a pet-friendly policy.', japanese: 'ペット同伴可能です。', category: 'Facilities' },
  { english: 'The hotel provides free airport shuttle.', japanese: '無料空港シャトルがございます。', category: 'Facilities' },
  { english: 'The hotel has a helipad.', japanese: 'ヘリポートがございます。', category: 'Facilities' },
  { english: 'The hotel offers valet parking.', japanese: 'バレットパーキングがございます。', category: 'Facilities' },
  { english: 'The hotel has a tennis court.', japanese: 'テニスコートがございます。', category: 'Facilities' },
  { english: 'The hotel provides free coffee in the lobby.', japanese: 'ロビーで無料のコーヒーをご提供しております。', category: 'Facilities' },

  // Directions (30 phrases)
  { english: 'The elevator is on your right.', japanese: 'エレベーターは右手にございます。', category: 'Directions' },
  { english: 'Take the stairs to the second floor.', japanese: '2階まで階段をお使いください。', category: 'Directions' },
  { english: 'The exit is at the end of the corridor.', japanese: '出口は廊下の突き当たりにございます。', category: 'Directions' },
  { english: 'Turn right at the next corner.', japanese: '次の角を右に曲がってください。', category: 'Directions' },
  { english: 'It\'s on the opposite side of the building.', japanese: '建物の反対側にございます。', category: 'Directions' },
  { english: 'Go straight ahead.', japanese: 'まっすぐ進んでください。', category: 'Directions' },
  { english: 'The nearest convenience store is a 5-minute walk.', japanese: '一番近いコンビニは徒歩5分です。', category: 'Directions' },
  { english: 'The station is straight ahead and turn left.', japanese: '駅はまっすぐ進んで左に曲がったところです。', category: 'Directions' },
  { english: 'Use the stairs in case of emergency.', japanese: '緊急時は階段をご利用ください。', category: 'Directions' },
  { english: 'The hotel is located in the city center.', japanese: 'ホテルは市街地にございます。', category: 'Directions' },
  { english: 'The nearest subway station is 3 minutes away.', japanese: '最寄りの地下鉄駅まで3分です。', category: 'Directions' },
  { english: 'The hotel is near the airport.', japanese: 'ホテルは空港の近くにございます。', category: 'Directions' },
  { english: 'The hotel is within walking distance of the beach.', japanese: 'ホテルからビーチまで徒歩圏内です。', category: 'Directions' },
  { english: 'The hotel is close to the train station.', japanese: 'ホテルは駅から近いです。', category: 'Directions' },
  { english: 'The hotel is in the business district.', japanese: 'ホテルはビジネス街にございます。', category: 'Directions' },
  { english: 'The hotel is surrounded by restaurants.', japanese: 'ホテルの周りにはレストランがたくさんあります。', category: 'Directions' },
  { english: 'The hotel is near the shopping mall.', japanese: 'ホテルはショッピングモールの近くにございます。', category: 'Directions' },
  { english: 'The hotel is in the historic district.', japanese: 'ホテルは歴史地区にございます。', category: 'Directions' },
  { english: 'The hotel is close to the convention center.', japanese: 'ホテルはコンベンションセンターの近くにございます。', category: 'Directions' },
  { english: 'The hotel is near the university.', japanese: 'ホテルは大学の近くにございます。', category: 'Directions' },
  { english: 'The hotel is in the entertainment district.', japanese: 'ホテルはエンターテイメント地区にございます。', category: 'Directions' },
  { english: 'The hotel is close to the hospital.', japanese: 'ホテルは病院の近くにございます。', category: 'Directions' },
  { english: 'The hotel is near the park.', japanese: 'ホテルは公園の近くにございます。', category: 'Directions' },
  { english: 'The hotel is in the financial district.', japanese: 'ホテルは金融街にございます。', category: 'Directions' },
  { english: 'The hotel is close to the museum.', japanese: 'ホテルは博物館の近くにございます。', category: 'Directions' },
  { english: 'The hotel is near the theater.', japanese: 'ホテルは劇場の近くにございます。', category: 'Directions' },
  { english: 'The hotel is in the residential area.', japanese: 'ホテルは住宅街にございます。', category: 'Directions' },
  { english: 'The hotel is close to the stadium.', japanese: 'ホテルはスタジアムの近くにございます。', category: 'Directions' },
  { english: 'The hotel is near the harbor.', japanese: 'ホテルは港の近くにございます。', category: 'Directions' },
  { english: 'The hotel is in the tourist area.', japanese: 'ホテルは観光地区にございます。', category: 'Directions' },

  // Requests (30 phrases)
  { english: 'Could you please wake me up at 7 AM?', japanese: '朝7時にモーニングコールをお願いできますか？', category: 'Requests' },
  { english: 'I need extra towels, please.', japanese: 'タオルを追加でお願いします。', category: 'Requests' },
  { english: 'Could you bring me some ice?', japanese: '氷を持ってきていただけますか？', category: 'Requests' },
  { english: 'I would like to make a reservation for dinner.', japanese: 'ディナーの予約をお願いしたいのですが。', category: 'Requests' },
  { english: 'Can you help me with my luggage?', japanese: '荷物のお手伝いをしていただけますか？', category: 'Requests' },
  { english: 'Could you please clean my room?', japanese: 'お部屋の清掃をお願いできますか？', category: 'Requests' },
  { english: 'I need more pillows, please.', japanese: '枕をもう少しお願いします。', category: 'Requests' },
  { english: 'Could you bring me a blanket?', japanese: '毛布を持ってきていただけますか？', category: 'Requests' },
  { english: 'I would like to order room service.', japanese: 'ルームサービスを注文したいのですが。', category: 'Requests' },
  { english: 'Could you please change my room?', japanese: 'お部屋を変更していただけますか？', category: 'Requests' },
  { english: 'I need a wake-up call at 6 AM.', japanese: '朝6時にモーニングコールをお願いします。', category: 'Requests' },
  { english: 'Could you please bring me some water?', japanese: 'お水を持ってきていただけますか？', category: 'Requests' },
  { english: 'I would like to extend my stay.', japanese: '延泊をお願いしたいのですが。', category: 'Requests' },
  { english: 'Could you please help me with the safe?', japanese: '金庫の使い方を教えていただけますか？', category: 'Requests' },
  { english: 'I need to use the business center.', japanese: 'ビジネスセンターを使いたいのですが。', category: 'Requests' },
  { english: 'Could you please arrange a taxi?', japanese: 'タクシーを手配していただけますか？', category: 'Requests' },
  { english: 'I would like to make a phone call.', japanese: '電話をかけたいのですが。', category: 'Requests' },
  { english: 'Could you please help me with the Wi-Fi?', japanese: 'Wi-Fiの設定を手伝っていただけますか？', category: 'Requests' },
  { english: 'I need to send a fax.', japanese: 'ファックスを送りたいのですが。', category: 'Requests' },
  { english: 'Could you please help me with the TV?', japanese: 'テレビの使い方を教えていただけますか？', category: 'Requests' },
  { english: 'I would like to book a tour.', japanese: 'ツアーを予約したいのですが。', category: 'Requests' },
  { english: 'Could you please help me with the air conditioning?', japanese: 'エアコンの使い方を教えていただけますか？', category: 'Requests' },
  { english: 'I need to use the laundry service.', japanese: 'ランドリーサービスを使いたいのですが。', category: 'Requests' },
  { english: 'Could you please help me with the shower?', japanese: 'シャワーの使い方を教えていただけますか？', category: 'Requests' },
  { english: 'I would like to make a reservation at the restaurant.', japanese: 'レストランの予約をお願いしたいのですが。', category: 'Requests' },
  { english: 'Could you please help me with the safe deposit box?', japanese: '貴重品預かりの使い方を教えていただけますか？', category: 'Requests' },
  { english: 'I need to use the gym.', japanese: 'ジムを使いたいのですが。', category: 'Requests' },
  { english: 'Could you please help me with the minibar?', japanese: 'ミニバーの使い方を教えていただけますか？', category: 'Requests' },
  { english: 'I would like to make a complaint.', japanese: '苦情を申し上げたいのですが。', category: 'Requests' },
  { english: 'Could you please help me with the elevator?', japanese: 'エレベーターの使い方を教えていただけますか？', category: 'Requests' },

  // Problems (30 phrases)
  { english: 'There seems to be a problem with the air conditioning.', japanese: 'エアコンに問題があるようです。', category: 'Problems' },
  { english: 'The TV is not working properly.', japanese: 'テレビが正常に動作しません。', category: 'Problems' },
  { english: 'I lost my room key.', japanese: '部屋のキーをなくしてしまいました。', category: 'Problems' },
  { english: 'The hot water is not working.', japanese: 'お湯が出ません。', category: 'Problems' },
  { english: 'There is too much noise from the next room.', japanese: '隣の部屋から騒音が聞こえます。', category: 'Problems' },
  { english: 'The Wi-Fi is not working.', japanese: 'Wi-Fiが接続できません。', category: 'Problems' },
  { english: 'The safe is not opening.', japanese: '金庫が開きません。', category: 'Problems' },
  { english: 'The toilet is not flushing properly.', japanese: 'トイレが流れません。', category: 'Problems' },
  { english: 'The lights are not working.', japanese: '電気がつきません。', category: 'Problems' },
  { english: 'The door is not locking properly.', japanese: 'ドアが正しく閉まりません。', category: 'Problems' },
  { english: 'The shower is not working.', japanese: 'シャワーが出ません。', category: 'Problems' },
  { english: 'The minibar is not cold enough.', japanese: 'ミニバーが冷えていません。', category: 'Problems' },
  { english: 'The bed is too hard.', japanese: 'ベッドが硬すぎます。', category: 'Problems' },
  { english: 'The room is too cold.', japanese: '部屋が寒すぎます。', category: 'Problems' },
  { english: 'The room is too hot.', japanese: '部屋が暑すぎます。', category: 'Problems' },
  { english: 'The curtains are not closing properly.', japanese: 'カーテンが正しく閉まりません。', category: 'Problems' },
  { english: 'The phone is not working.', japanese: '電話が使えません。', category: 'Problems' },
  { english: 'The safe deposit box is not working.', japanese: '貴重品預かりが使えません。', category: 'Problems' },
  { english: 'The elevator is not working.', japanese: 'エレベーターが動きません。', category: 'Problems' },
  { english: 'The room service is not answering.', japanese: 'ルームサービスに電話がつきません。', category: 'Problems' },
  { english: 'The laundry service lost my clothes.', japanese: 'ランドリーサービスで服をなくされました。', category: 'Problems' },
  { english: 'The room is not clean.', japanese: '部屋が汚れています。', category: 'Problems' },
  { english: 'The bathroom is not clean.', japanese: 'バスルームが汚れています。', category: 'Problems' },
  { english: 'The towels are dirty.', japanese: 'タオルが汚れています。', category: 'Problems' },
  { english: 'The sheets are not clean.', japanese: 'シーツが汚れています。', category: 'Problems' },
  { english: 'The room smells bad.', japanese: '部屋が臭います。', category: 'Problems' },
  { english: 'The bathroom smells bad.', japanese: 'バスルームが臭います。', category: 'Problems' },
  { english: 'The air conditioning is too loud.', japanese: 'エアコンの音がうるさすぎます。', category: 'Problems' },
  { english: 'The heating is not working.', japanese: '暖房が効きません。', category: 'Problems' },
  { english: 'The room is too small.', japanese: '部屋が狭すぎます。', category: 'Problems' },

  // Phone (30 phrases)
  { english: 'How can I make an outside call?', japanese: '外線に電話をかけるにはどうすればよいですか？', category: 'Phone' },
  { english: 'What is the dialing code for international calls?', japanese: '国際電話のかけ方はどうすればよいですか？', category: 'Phone' },
  { english: 'I would like to make a collect call.', japanese: 'コレクトコールで電話をかけたいのですが。', category: 'Phone' },
  { english: 'Can you connect me to room 1205?', japanese: '1205号室に電話を回していただけますか？', category: 'Phone' },
  { english: 'I have a message for Mr. Smith.', japanese: 'スミス様への伝言がございます。', category: 'Phone' },
  { english: 'Good morning, this is the front desk.', japanese: 'おはようございます、フロントでございます。', category: 'Phone' },
  { english: 'How can I reach room service?', japanese: 'ルームサービスにはどうすれば連絡できますか？', category: 'Phone' },
  { english: 'What is the extension for housekeeping?', japanese: 'ハウスキーピングの内線番号は何番ですか？', category: 'Phone' },
  { english: 'Can you transfer me to the concierge?', japanese: 'コンシェルジュに電話を回していただけますか？', category: 'Phone' },
  { english: 'I would like to make a local call.', japanese: '市内通話をかけたいのですが。', category: 'Phone' },
  { english: 'How much does it cost to call overseas?', japanese: '海外通話の料金はいくらですか？', category: 'Phone' },
  { english: 'Can you help me with the phone system?', japanese: '電話システムの使い方を教えていただけますか？', category: 'Phone' },
  { english: 'I need to make an emergency call.', japanese: '緊急電話をかけたいのですが。', category: 'Phone' },
  { english: 'Can you connect me to the manager?', japanese: 'マネージャーに電話を回していただけますか？', category: 'Phone' },
  { english: 'I would like to speak to the concierge.', japanese: 'コンシェルジュと話したいのですが。', category: 'Phone' },
  { english: 'Can you help me with the directory?', japanese: '電話帳の使い方を教えていただけますか？', category: 'Phone' },
  { english: 'I need to call a taxi.', japanese: 'タクシーを呼びたいのですが。', category: 'Phone' },
  { english: 'Can you connect me to the restaurant?', japanese: 'レストランに電話を回していただけますか？', category: 'Phone' },
  { english: 'I would like to make a wake-up call.', japanese: 'モーニングコールをお願いしたいのですが。', category: 'Phone' },
  { english: 'Can you help me with the voicemail?', japanese: 'ボイスメールの使い方を教えていただけますか？', category: 'Phone' },
  { english: 'I need to call the front desk.', japanese: 'フロントに電話をかけたいのですが。', category: 'Phone' },
  { english: 'Can you connect me to housekeeping?', japanese: 'ハウスキーピングに電話を回していただけますか？', category: 'Phone' },
  { english: 'I would like to speak to the manager.', japanese: 'マネージャーと話したいのですが。', category: 'Phone' },
  { english: 'Can you help me with the phone directory?', japanese: '電話帳の使い方を教えていただけますか？', category: 'Phone' },
  { english: 'I need to make a reservation by phone.', japanese: '電話で予約を取りたいのですが。', category: 'Phone' },
  { english: 'Can you connect me to room service?', japanese: 'ルームサービスに電話を回していただけますか？', category: 'Phone' },
  { english: 'I would like to speak to the concierge.', japanese: 'コンシェルジュと話したいのですが。', category: 'Phone' },
  { english: 'Can you help me with the phone system?', japanese: '電話システムの使い方を教えていただけますか？', category: 'Phone' },
  { english: 'I need to call the front desk.', japanese: 'フロントに電話をかけたいのですが。', category: 'Phone' },
  { english: 'Can you connect me to the manager?', japanese: 'マネージャーに電話を回していただけますか？', category: 'Phone' },

  // Emergency (30 phrases)
  { english: 'Is there an emergency exit nearby?', japanese: '近くに非常口はありますか？', category: 'Emergency' },
  { english: 'Where is the fire extinguisher?', japanese: '消火器はどこにありますか？', category: 'Emergency' },
  { english: 'Please call an ambulance immediately.', japanese: 'すぐに救急車を呼んでください。', category: 'Emergency' },
  { english: 'I need to report a medical emergency.', japanese: '医療緊急事態を報告する必要があります。', category: 'Emergency' },
  { english: 'Please contact the police.', japanese: '警察に連絡してください。', category: 'Emergency' },
  { english: 'There is a fire in the building.', japanese: '建物で火事が発生しています。', category: 'Emergency' },
  { english: 'I need immediate medical attention.', japanese: 'すぐに医療処置が必要です。', category: 'Emergency' },
  { english: 'Please call 911.', japanese: '119番に電話してください。', category: 'Emergency' },
  { english: 'There is an emergency in room 1205.', japanese: '1205号室で緊急事態が発生しています。', category: 'Emergency' },
  { english: 'I need to evacuate immediately.', japanese: 'すぐに避難する必要があります。', category: 'Emergency' },
  { english: 'Please help me get to safety.', japanese: '安全な場所に避難するのを手伝ってください。', category: 'Emergency' },
  { english: 'There is a gas leak.', japanese: 'ガス漏れが発生しています。', category: 'Emergency' },
  { english: 'I need to report a crime.', japanese: '犯罪を報告する必要があります。', category: 'Emergency' },
  { english: 'Please call the fire department.', japanese: '消防署に電話してください。', category: 'Emergency' },
  { english: 'There is a power outage.', japanese: '停電が発生しています。', category: 'Emergency' },
  { english: 'I need to contact my embassy.', japanese: '大使館に連絡する必要があります。', category: 'Emergency' },
  { english: 'Please help me find the emergency exit.', japanese: '非常口を見つけるのを手伝ってください。', category: 'Emergency' },
  { english: 'There is a security threat.', japanese: 'セキュリティ上の脅威があります。', category: 'Emergency' },
  { english: 'I need to report a missing person.', japanese: '行方不明者を報告する必要があります。', category: 'Emergency' },
  { english: 'Please call the security office.', japanese: 'セキュリティオフィスに電話してください。', category: 'Emergency' },
  { english: 'There is a water leak.', japanese: '水漏れが発生しています。', category: 'Emergency' },
  { english: 'I need to report a theft.', japanese: '盗難を報告する必要があります。', category: 'Emergency' },
  { english: 'Please help me contact my family.', japanese: '家族に連絡するのを手伝ってください。', category: 'Emergency' },
  { english: 'There is a medical emergency.', japanese: '医療緊急事態が発生しています。', category: 'Emergency' },
  { english: 'I need to report an accident.', japanese: '事故を報告する必要があります。', category: 'Emergency' },
  { english: 'Please call the hospital.', japanese: '病院に電話してください。', category: 'Emergency' },
  { english: 'There is a natural disaster.', japanese: '自然災害が発生しています。', category: 'Emergency' },
  { english: 'I need to evacuate the building.', japanese: '建物から避難する必要があります。', category: 'Emergency' },
  { english: 'Please help me find shelter.', japanese: '避難所を見つけるのを手伝ってください。', category: 'Emergency' },
  { english: 'There is a terrorist threat.', japanese: 'テロの脅威があります。', category: 'Emergency' },

  // Small Talk (30 phrases)
  { english: 'How is the weather today?', japanese: '今日の天気はいかがですか？', category: 'Small Talk' },
  { english: 'Are you enjoying your stay?', japanese: 'ご滞在はいかがでしょうか？', category: 'Small Talk' },
  { english: 'Is this your first time visiting our city?', japanese: '当市へのご訪問は初めてですか？', category: 'Small Talk' },
  { english: 'Do you have any plans for today?', japanese: '今日は何かご予定はありますか？', category: 'Small Talk' },
  { english: 'I hope you have a wonderful day.', japanese: '素晴らしい一日をお過ごしください。', category: 'Small Talk' },
  { english: 'Good morning! How may I help you?', japanese: 'おはようございます。何かお手伝いできることはございますか？', category: 'Small Talk' },
  { english: 'Have a pleasant stay!', japanese: '快適なご滞在をお過ごしください！', category: 'Small Talk' },
  { english: 'How was your flight?', japanese: 'フライトはいかがでしたか？', category: 'Small Talk' },
  { english: 'Are you here for business or pleasure?', japanese: 'ビジネスでいらっしゃいましたか、それとも観光ですか？', category: 'Small Talk' },
  { english: 'How long are you staying?', japanese: 'どれくらいの期間お泊りですか？', category: 'Small Talk' },
  { english: 'Where are you from?', japanese: 'どちらからいらっしゃいましたか？', category: 'Small Talk' },
  { english: 'Have you been to our city before?', japanese: '当市には以前いらっしゃったことがありますか？', category: 'Small Talk' },
  { english: 'What brings you to our city?', japanese: '当市にいらっしゃった理由は何ですか？', category: 'Small Talk' },
  { english: 'Are you enjoying the local cuisine?', japanese: '地元の料理はいかがですか？', category: 'Small Talk' },
  { english: 'Have you visited any local attractions?', japanese: '地元の観光スポットは訪れましたか？', category: 'Small Talk' },
  { english: 'How do you like our hotel?', japanese: '当ホテルはいかがですか？', category: 'Small Talk' },
  { english: 'Is there anything special you would like to see?', japanese: '特別に見たいものはありますか？', category: 'Small Talk' },
  { english: 'Have you tried our restaurant?', japanese: '当ホテルのレストランはご利用になりましたか？', category: 'Small Talk' },
  { english: 'Are you comfortable with your room?', japanese: 'お部屋はご満足いただけていますか？', category: 'Small Talk' },
  { english: 'Do you need any recommendations?', japanese: '何かおすすめが必要ですか？', category: 'Small Talk' },
  { english: 'How is your family?', japanese: 'ご家族はいかがですか？', category: 'Small Talk' },
  { english: 'Are you traveling alone?', japanese: 'お一人でのご旅行ですか？', category: 'Small Talk' },
  { english: 'Have you made any friends here?', japanese: 'こちらでお友達はできましたか？', category: 'Small Talk' },
  { english: 'What do you think of our service?', japanese: '当ホテルのサービスはいかがですか？', category: 'Small Talk' },
  { english: 'Are you planning to visit again?', japanese: 'またいらっしゃる予定はありますか？', category: 'Small Talk' },
  { english: 'How can we make your stay better?', japanese: 'より良いご滞在のために何かできることはありますか？', category: 'Small Talk' },
  { english: 'Have you enjoyed your time here?', japanese: 'こちらでの時間は楽しくお過ごしですか？', category: 'Small Talk' },
  { english: 'Is there anything we can improve?', japanese: '改善できる点はありますか？', category: 'Small Talk' },
  { english: 'Thank you for choosing our hotel.', japanese: '当ホテルをお選びいただき、ありがとうございます。', category: 'Small Talk' },
  { english: 'We hope to see you again soon.', japanese: 'また近いうちにお会いできることを楽しみにしております。', category: 'Small Talk' }
];

// TypeScriptファイルを生成
const tsContent = `import { Phrase } from '../utils/csvParser';

export const phraseData: Phrase[] = ${JSON.stringify(cleanPhrases.map((phrase, index) => ({
  id: `phrase_${index + 1}`,
  english: phrase.english,
  japanese: phrase.japanese,
  category: phrase.category
})), null, 2)};
`;

// ファイルに書き込み
const outputPath = path.join(__dirname, '../src/data/phraseData.ts');
fs.writeFileSync(outputPath, tsContent);

console.log(`Generated ${cleanPhrases.length} unique phrases`);
console.log('Categories:', [...new Set(cleanPhrases.map(p => p.category))]);
